### ISSUE TITLE
img tag seems not working

### ISSUE THREAD

**Issue by dbrw** [IftekherSunny/PDF#1]
Hi, IftekherSunny.
I found your script is helpfull, but i couldn't use `img` tag on my template.
here is the script:

```
<img alt="logo" src="img/logo.png" width="300" height="80" />
```

The rendered pdf just show a box with grey border and the alt text, which is look similar to not found image but when I run the code above directly, it shown the logo.

Could you help me with this?

**Comment by IftekherSunny** [comment]
@dbrw 

Use image tag like as I shown in the below..

```
<img alt="logo" width="300" height="80"
src="data:image/png;base64,<?php echo base64_encode( file_get_contents( '/path/to/img/logo.png' ) ) ?>"
/>
```

Here /path/to/img/logo.png is the absolute path of your image.

**Comment by dbrw** [comment]
Thank you, it works now.
