### ISSUE TITLE
save pdf to folder

### ISSUE THREAD

**Issue by joe-complete-grp** [IftekherSunny/PDF#2]
Hi maybe Im missing something obvious! but how do I save the pdf to a folder on the server? - my process will be a cron job so it needs to be automated.

**Comment by IftekherSunny** [comment]
Hi @joe-complete-grp 

Here is an example for saving generated pdf to a folder

```
$pdf = new Sun\PDF;

$data = $pdf->output("<h1>Hello world</h1>");

file_put_contents('joe.pdf', $data);
```

**Comment by joe-complete-grp** [comment]
ah thanks, I was trying to return it to a CURL call from a different file and do the file_put_contents from there but was getting a corrupt pdf. 

Great simple library :)
Cheers
